# Generated by Django 6.0.3 on 2026-03-17 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponMemory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_type', models.CharField(choices=[('CODE', 'Code'), ('AUTO_APPLY', 'Auto Apply'), ('VOUCHER', 'Voucher'), ('CASHBACK', 'Cashback')], default='CODE', max_length=20)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('discount_text', models.CharField(blank=True, max_length=100, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('remind_before_minutes', models.IntegerField(default=1440)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_at', '-created_at'],
            },
        ),
    ]
