# Generated by Django 6.0.3 on 2026-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarconnection',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='sync_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('ERROR', 'Error')], default='IDLE', max_length=20),
        ),
    ]
